### PR TITLE
Added setting, that defines, at which point should be .git removed.

### PR DESCRIPTION
**Pull request by tvrzna**
Last year I had mentioned, that in some cases it could be required to have .git folder during build (e.g. enhancing application version). For this specific reason I've added new configuration named `git_folder_handling`.
This config could be set to three options:
- **DELETE_BEFORE_BUILD** - the default option, that removes .git folder before build starts. This is original behaviour.
- **DELETE_AFTER_BUILD** - this option covers mentioned state, when .git folder is available during build, but is removed before zipped artifact is created.
- **DISABLE_DELETE** - the option, that leaves .git folder at project during build and also is zipped to artifact.

### CODE REVIEW

**Comment by gsantner** [comment]
I would recommend to use e.g. `BUILD_DELETE_SOURCE_BEFORE_BUILD`, `BUILD_DELETE_SOURCE_BEFORE_ARCHIVE`, `BUILD_DELETE_SOURCE_DISABLE`,

**Comment by tvrzna** [comment]
That would be quite an overkill, those values are Enum, so standard usage is with enum name. The default value is `GitFolderHandling.DELETE_BEFORE_BUILD`. Maybe the enum could have better name.

**Comment by NiklasRosenstein** [comment]
LGTM, but could you move the enum definition into a module other than `flux_config`? (Because it is intended to only supply configuration values, not any types that are part of the config's logic)

**Comment by tvrzna** [comment]
That's a good point. I'll create common enum module later today, as soon as I get to my computer.

**Pull request merged**
