### PR TITLE
Added possibility to generate/remove and use custom SSH keypair per each repository

### PR DESCRIPTION
**Pull request by tvrzna**
References #53 

- Added option to Generate SSH keypair/Remove SSH keypair in View Repo Options.
- Generating uses newly added dependency [`cryptography`](https://pypi.org/project/cryptography/) (>=2.0).
- Newly generated keys are stored in new folder customs (see `customs_dir` in `flux_config.py`).
- Private key requires to have permissions set to `600` on Linux. **NOTE:** for this point I would like to ask someone to try it on Windows, if it works correctly.
- Public key is accessible on Edit Repo page (the reason is, that almost all informations are there and this page is not that frequently visited).

If repo has custom SSH key, it is used in `views.ping_repo()` and `build.do_build_()` methods by `GIT_SSH_COMMAND`, where is key defined as identity_file.

### CODE REVIEW

**Comment by tvrzna** [comment]
> I think it would make more sense to have the Generate and Remove SSH Keypair buttons in the same page (Edit Repo). When there is no key associated with the repository, there would just be a "Generate SSH Keypair" button. If there is, it displays the public key (as it does currently) and below or above that the "Remove SSH Keypair" button.

I agree, the reasons I put it there is to prevent generating it on new repo (e.g. missing name, name going to be changed/drafted detail being abandoned) and the fact, that it would cause reload of page with potentionally unsaved changes on repo. First reason should be definitely resolved by hiding this on new repo detail.

**Comment by tvrzna** [comment]
Generate SSH Keypair button is now part of toolbar at Edit Repo page.
Remove SSH Keypair button is moved below Public Key, floating on right of Save button.

These buttons are visible only for existing repository.

**Comment by NiklasRosenstein** [comment]
Looks good, thanks! :) It should work on Windows, it doesn't care about permissions.

**Comment by NiklasRosenstein** [comment]
I've moved the Generate SSH Keypair button to the same location as the Remove SSH Keypair button.

**Pull request merged**
