### PR TITLE
Add option to load flux config specified by cmdline arg

### PR DESCRIPTION
**Pull request by gsantner**
Add option to load flux config specified by cmdline arg

### CODE REVIEW

**Comment by gsantner** [comment]
Honestly - I think this whole thing is anyway borked. This should be a normal config file, not a python executeable, and not loaded into global namespace. My opinion on this

**Comment by gsantner** [comment]
Did you hit the wrong button? :D

**Comment by NiklasRosenstein** [comment]
Using just Python code for configuration gives a lot of flexibility.

**Comment by NiklasRosenstein** [comment]
> Did you hit the wrong button? :D

I made some changes on top of the PR ;)

https://github.com/NiklasRosenstein/flux-ci/commit/75a7e3a19620927b1bb19319e2fce23be2dc4171

**Comment by gsantner** [comment]
Ah okay! :+1:  :D

**Pull request merged**
