### PR TITLE
Cleanup, CLI and Docker update

### PR DESCRIPTION
**Pull request by NiklasRosenstein**
* Some code cleanup
* Added `setup.py` script which installs a `flux-ci` command
* Removed `flux_run.py`, use `flux-ci --web` instead
* Update `Dockerfile` and instructions to use Docker
* Support `FLUX_SERVER_NAME` environment variable
* Increment version number in `flux/__init__.py` to 1.1.0 (final after this PR and #43)

### CODE REVIEW

**Comment by tvrzna** [comment]
I have to admit, I miss the option just download, install requirements and run. I'm not big fan of installation, because 1) I'm not into python so every my line is try-error method and I have to debug a lot. 2) I'm used to just unpack and run on server machines. I know, there is still possibility to just install/build into virtualenv, but complicates the simplicity. Or am I missing something and there is still option to run something executable?

**Comment by NiklasRosenstein** [comment]
Hm, I don't quite see how the install script complicates things. Instead of

    $ pip install -r requirements.txt

You just do

    $ pip install .

Or, more commonly for installations that you commonly upgrade or develop on

    $ pip install -e .

If you haven't set up your `PATH` so commands that Pip installs are not available, I recommend you do so. If you don't want/can't, you can still run Flux with

    $ python -m flux.main

:)

**Comment by tvrzna** [comment]
I was missing that point, thank you! It works now :)

**Comment by gsantner** [comment]
I'm too with @tvrzna - if possible i prefer to just do python3 flux-ci   flux_run or like that. especially for doing development now it's a lot easier to just restart by ctrl-c, up, enter ;)

**Comment by NiklasRosenstein** [comment]
You probably don't have the path where the scripts for user installs are placed in your PATH environment variable. I know for a fact that it's not automatically added on Windows by the Python installer, not sure about Linux.

I' recommend you add that path, somethinh like %APPDATA%\Python\Python3\Scripts on Windows and ~/.local/bin on Linux.

Alternatively, as mentioned before, give

    python -m flux.main --web

a try. :)

**Comment by gsantner** [comment]
do you have matrix or something? makes discussion easier

**Comment by NiklasRosenstein** [comment]
No idea what "matrix" you mean. Some kind of chat service? I know about Gitter, we could use that for example.

**Comment by gsantner** [comment]
https://about.riot.im/

https://matrix.to/#/@gsantner:matrix.org

**Comment by NiklasRosenstein** [comment]
I'll chexk this out tomorrow.

**Pull request merged**
